title: 유미의 투자이야기
author:
  name: Jaehun Sim
  email: tapu1125@gmail.com
description: 투자 이야기를 재밌게 풀어내는 블로그입니다. 2025년 1월부터 시작했습니다.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md
minima:
  skin: dark
  date_format: "%Y %b %-d"
